### ISSUE TITLE
Undefined Index issues in ensureBaseConfig (minor issue)

### ISSUE THREAD

**Issue by Mhbuur** [Jemt/StandardizedPaymentProviderInterface#4]
I get

Notice: Undefined index: ConfigPath in .../PSPI/PSPInterface.php on line 410
Notice: Undefined index: ConfigPath in .../PSPI/PSPInterface.php on line 412

in ensureBaseConfig..

**Comment by Jemt** [comment]
Confirmed.
TODO: Either make the parameter optional or add it to Config.php.

**Comment by Jemt** [comment]
Fixed - ConfigPath parameter is now optional.
https://github.com/Jemt/PaymentServiceProviderInterface/commit/9357bfef101dc2529200c395377c0eae5b797b8f
