### ISSUE TITLE
Use responsive design (DIBS)

### ISSUE THREAD

**Issue by Mhbuur** [Jemt/StandardizedPaymentProviderInterface#5]
To use the modern responsive DIBS payment window, add this parameter to the form:

`<input type="hidden" name="decorator" value="responsive">`

**Comment by Jemt** [comment]
Thanks, good idea. Note to self: the decorator option is described here: http://tech.dibspayment.com/D2/Hosted/Input_parameters/Standard

**Comment by Jemt** [comment]
Thanks @Mhbuur - issue has been resolved.
